version: '3'

services:

  app-node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app-node
    entrypoint: dockerize -wait tcp://db-node:3306 -timeout 30s node index.js
    tty: true
    networks:
      - network-node
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db-node

  nginx-node:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-desafio
    networks:
      - network-node
    ports:
      - "8080:80"
    tty: true
    volumes:
      - ./node:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - db-node

  db-node:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-node
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network-node

networks:
  network-node:
    driver: bridge